apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp

spec:
  containers:
    - name: api
      image: apitokenizador-api:latest
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: api-volume
          mountPath: /usr/src/app
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379
      volumeMounts:
        - name: redis-volume
          mountPath: /data
  volumes:
    - name: api-volume
      hostPath:
        path: /root/proyectoculqi
    - name: redis-volume
      emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: myservice

spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
