version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    command: npm run start:dev  # Run a command against the development stage of the image
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis: # Name of container
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
